# Generated by Django 3.1.3 on 2020-12-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesupload',
            name='emai',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='filesupload',
            name='jobdes',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='filesupload',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='filesupload',
            name='workex',
            field=models.IntegerField(null=True),
        ),
    ]
