# Generated by Django 3.1.3 on 2020-12-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_auto_20201201_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesupload',
            name='phonenumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
