# Generated by Django 3.1.4 on 2020-12-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjobtp',
            name='jobdes',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
