# Generated by Django 3.1.3 on 2020-12-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201205_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='jb',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
