# Generated by Django 3.1.4 on 2020-12-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201206_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtype',
            name='jb',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
