# Generated by Django 3.1.3 on 2020-12-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201207_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjobtp',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
