# Generated by Django 3.1.3 on 2020-12-07 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userjobtp_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtype',
            old_name='jobdescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='jobtype',
            old_name='experince',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='jobtype',
            old_name='jobtype',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='userjobtp',
            old_name='dob',
            new_name='DOB',
        ),
        migrations.RenameField(
            model_name='userjobtp',
            old_name='fname',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='userjobtp',
            old_name='jobdes',
            new_name='Last_name',
        ),
        migrations.RenameField(
            model_name='userjobtp',
            old_name='lname',
            new_name='Position',
        ),
        migrations.RenameField(
            model_name='userjobtp',
            old_name='workex',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='userjobtp',
            old_name='emai',
            new_name='mail_ID',
        ),
    ]
