# Generated by Django 3.1.3 on 2020-12-07 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201207_1144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userJobTp',
            new_name='Candidates',
        ),
        migrations.RenameModel(
            old_name='jobType',
            new_name='Vacancies',
        ),
    ]
