# Generated by Django 3.1.3 on 2020-12-07 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201207_1149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidates',
            new_name='Candidate',
        ),
        migrations.RenameModel(
            old_name='Vacancies',
            new_name='Vacancie',
        ),
    ]
