# Generated by Django 3.1.4 on 2020-12-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_jobtype_jb'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='ex',
            field=models.IntegerField(default=0, verbose_name=range(1, 21)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobtype',
            name='lc',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobtype',
            name='sl',
            field=models.IntegerField(default=0, verbose_name=range(1, 3000000)),
            preserve_default=False,
        ),
    ]
