# Generated by Django 3.1.3 on 2020-12-07 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201206_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtype',
            old_name='ex',
            new_name='experince',
        ),
        migrations.RenameField(
            model_name='jobtype',
            old_name='jb',
            new_name='jobdescription',
        ),
        migrations.RenameField(
            model_name='jobtype',
            old_name='jt',
            new_name='jobtype',
        ),
        migrations.RenameField(
            model_name='jobtype',
            old_name='lc',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='jobtype',
            old_name='sl',
            new_name='salary',
        ),
    ]
